version: '3.1'

services:
  app:
    image: 'sms'
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: app
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sms?useSSL=false&allowPublicKeyRetrieval=true&serverTimeZone=UTC&useLegacyDatatimeCode=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql