GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY0NzI2MzMxMiwiZXhwIjoxNjQ3MjYzMzM3fQ.ZljtLXT0TNpk16vMghKMa2wcHsjCTQgXT-z5CMlhFgw

###


###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY0NzI2Nzc3M30.zPU3yzQP5Ajdh5DTfyNJsr4sMpHcRJBkEzdX48f4duo"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY0NzI2Nzc3M30.zPU3yzQP5Ajdh5DTfyNJsr4sMpHcRJBkEzdX48f4duo"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}